---
collections:
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.eda
  - name: infra.aap_configuration
    version: "3.7.0"
  - name: infra.aap_configuration_extended
    version: "=2.0.0"

...
