---
eda_decision_environments:
  - name: "Hub Default Decision Environment"
    description: ""
    image_url: "aap2.j114.army.mil/de-supported-rhel8:latest"
    organization: "Default"
    eda_credential: "Hub Decision Environment Container Registry"
...
