download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/ansible-hub-1.0.2.tar.gz
format_version: 1.0.0
name: hub
namespace: ansible
server: https://console.redhat.com/api/automation-hub/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2025-09-17T20:59:29.741444Z'
  signature: '-----BEGIN PGP SIGNATURE-----


    iQIcBAABCAAGBQJoyyEGAAoJEOGkvXCKgoqtfaIP/3XVg81KKfMZROE3vn13q4fO

    0fBTyQqetOZzYPQ4VztfTWmFiUNyW0o8hzbCJB3FbxDtcpuiLYfqKNphc8U5nhMS

    bPJ+yhXrj4dsNhgs0FmlqqdRcadKkEDDJ6t2Ex0dSWFcDqpCwyO7OOuMORZARsOh

    iZ9GfObBN1+IoaluLKT36TRXQlXG3Bbw055T1clLaRvj4PEZq4oXe6l7T+p8STyt

    OgvphT6WnO3hWk+aRFtdoANKx65KbYAM0vEKvcRuEG/EJwB8GVyNvSqtRvcqN097

    BYIqnpFjl4xSVU6xm4UcvmSJwgqsRxOPsaT94jBnd4ZCW6Elxx4/vvzBceG52WCY

    7XfjLrRvoJScv5c2zj0Dx6UzJcAYvIu05WEBbctuLNm8+Z2EL+YG7pGBIQn7fOX/

    3Q2P2H9/s0yOUmaDqpO8b3LJkx2QoNvPlZwEW22jkRHbevbX/M16V6Q7nSgDtm7x

    YXEkdsaaxkdFNWdyrAu2rAfXOALCS/5NbJAD+ycUo8itT9bb8hMN6NZf+yqP+scD

    rSuEP64ZTVklontNTcgosUT9XmEZDJJevtWjfgMnEdOdQ1BmNt5dqYY47ZgY1W1T

    cnXwt6lS9BoBz4ux8IEOEi7tszoiM11ErtsbatRFg8B6uegSfBzEGtVin1VzhjjT

    9hgJkZsLMlUePp+WYQ46

    =qw1L

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 1.0.2
version_url: /api/automation-hub/v3/plugin/ansible/content/published/collections/index/ansible/hub/versions/1.0.2/
