download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/ansible-platform-2.5.20250702.tar.gz
format_version: 1.0.0
name: platform
namespace: ansible
server: https://console.redhat.com/api/automation-hub/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2025-06-25T01:26:32.797194Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIcBAABCAAGBQJoW1A+AAoJEOGkvXCKgoqtJ1oP/1tL283GZWzT9swOWuAJWgkb

    edW8IXsF4r5ekxnK8KNrhk2TKeog8FQNk/hnLlVawg50Rvwa+Oz1Px3IaRYVx3/a

    iui3+uwkEZ3n90wpnuE/6FEryD2/fBi7oEyDjcERw5LxGtJod33n4CYP8syqWVac

    VKsyAamr+9F7d4cM1w/LZtd398hyi8EmFHvlwl9Vv1tnxnl3ibwuzdUsB/FzZZON

    LaU+fAYNYPiSOn4Z0V9d86954UWTZT6BJsZ8+WnP6aNmWOX67wKr/YX81eAPxTTv

    ze+YfkBj5ZZIWJnX8zcfWpZ7COb8q4Ccg2addvjvCcF4yqI+0qNeYgEJKF5Ju9rn

    XYXNL8MZQfcaaWPYrKNTcOlacNMBZSCQjt0lisbwEwcnHVf+syMFn6t4GNqhPFgI

    uevpHbIYZDWs2fUfkD1bmZgqt7HWOp/w0mwkTogVzkYHFr/C3hnvlXXtZOzA/oiv

    3wdnn+OOq6naETwSrRu05YQeuy03YHfpnqARBqyZQSNIcqA4lxLeGkpPeFIdAwxc

    LDnek5zFrOy/lhn1587NeepGxTjLtVqfvaqGbr8+IgJ1FskDEHYBgxtfQq9ARiJ0

    24Tft8xHLB3sipTDTaqGuTmlQ7KIwfLYfdcf/XYGP7Jc7dJATMfm5uYgXMJSxyYJ

    ZkH42//8pb53PalPxBHc

    =uWxf

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 2.5.20250702
version_url: /api/automation-hub/v3/plugin/ansible/content/published/collections/index/ansible/platform/versions/2.5.20250702/
